### PR TITLE
Prevent Logstash starting issue

### PR DESCRIPTION
**Pull request by bertrandjamin**
As described in https://github.com/spujadas/elk-docker/issues/11 
"Logstash doesn't seem to start when JAVA_OPTS is set"

I have made the same modification than spujadas (comment rather than deletion)
But I can delete wrong lines if you prefer

I have tested and validated this change via a mounted volume on a fixed logstash init file

### CODE REVIEW

**Review by ypereirareis — COMMENTED** [review]
Hello and thanks.

Seems Ok but some vars are exported twice with your patch.  Have a look at the line following your exports.

**Comment by bertrandjamin** [comment]
Oups too late (or too early) commit.  
I fix it quickly :)

**Comment by ypereirareis** [comment]
It's me or your fix is... nowhere ? :smile:

**Comment by bertrandjamin** [comment]
Sorry It was not so quick finally 😅

**Pull request merged**
